# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a5421b05d518b96347fdba92c29c0330f8b98405b49c8a78f279993fabff34b9e1681d327bf3838e4da5419b7dfca100a8d0b9efd53d0e02a30ee03329625d2

test:
  secret_key_base: 5f24a3a619ca374c013a40ea25196062563fcde3b0b383a93889cf3a9897b40a61f2b887365edf819885c294ee521fa8b4ade5fa7537f43bba2393abc876b084

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
